Copy app code from course and add GIPHY
DawMas/18.8-wyszukiwarka-gifow pull request #1
Opened 2019-07-13 21:22 UTC by DawMas

Jeśli Twój projekt wyszukiwarki gifów jeszcze nie znalazł się na GitHubie, załóż teraz repozytorium i wyślij na nie kod projektu.

Dodałem klucze z GIPHY. Apka działa !

2019-07-14 04:50 UTC, lukaszewczak requested changes

2019-07-14 04:50 UTC, lukaszewczak commented on package.json
> +  "devDependencies": {
Zostaw tylko zależności potrzebne dla tego projektu

2019-07-14 04:50 UTC, lukaszewczak commented on components/Search.js
> +handleKeyUp: function(event){
Popraw proszę formatowanie

2019-07-14 20:11 UTC, DawMas commented on components/Search.js
> +handleKeyUp: function(event){
Zrobione ; )

2019-07-15 07:12 UTC, lukaszewczak approved these changes

2019-07-20 17:35 UTC, lukaszewczak approved these changes

2019-07-20 17:38 UTC, merged